### ISSUE TITLE
Server Betav201 Not working

### ISSUE THREAD

**Issue by Lotus6654** [DrummingFish/MonumentalModpack#4]
Hello, 
Just tu let you know that you don't have any libraries in the server file.
When you add them ans launch the server it crashes.
Log said that is was some problem with resonant engine ( mod)

Thanks for your amaizing work !

**Comment by DrummingFish** [comment]
Yeah I am aware of this problem. I neglected to test the server side when I released and now feel like an idiot. I will get it fixed either today or tomorrow.
