### ISSUE TITLE
Suggestion: Add BigReactors

### ISSUE THREAD

**Issue by recon88** [DrummingFish/MonumentalModpack#7]
I just found the pack and I'm missing BigReactors in it. Would it be possible to get that added? :3

**Comment by DrummingFish** [comment]
Been thinking about it. Would need some testing. I'll look into it.

**Comment by DrummingFish** [comment]
Messed around with it and I'm sorry to say it doesn't seem to balance very well. I'm not very fond of the mod anyway.

**Comment by recon88** [comment]
You could just higher the fuel usage if it's too easy. I think it's a must have for lategame to provide high amounts of power.

**Comment by DrummingFish** [comment]
I don't like the idea of late game just being able to create a multiblock and then you're set. There needs to be complexity to the solution, especially late game with the mods I have.
